export const baseKeywordQualifiers = [
  'What %',
  '% vs',
  'Can %',
  'Will %',
  'Which %',
  'What is the difference %',
  '% ideas',
  'Is %',
  '% alternatives',
  'What to do if %',
  'Should %',
  'When is %',
  'is %',
  'Why does %',
  '% tips',
  'Why doesn’t %',
  'When does %',
  'Best %',
  'Why can’t %',
]

export const conceptPluralQualifiers = [
  'What	%',
  'How much do %',
  '% vs',
  'Can %',
  'Ideas for	%',
  'Will	%',
  'Best % for	',
  'My % are	',
  'Which %',
  'How to make	%',
  'How often do	%',
  'Step by step instructions for	%',
  'What to do if	%',
  'What is the difference between	%',
  'When is	%',
  'Should	%',
  'Pros and cons of	%',
  'Ideas for improving	%',
  'Why do	%',
  '% alternatives',
  'How to fit	%',
  'Are %',
  'Why are	%',
  'What if	%',
  'Why do my	%',
  'When do	%',
  'are	%',
]

export const conceptSingularQualifiers = [
  'ideas %',
  'Why is %',
  '% vs',
  'Best % for',
  'Cheapest %',
  'tips %',
  'Prevent % from',
  'How to use %',
  'My % has started to',
  '% step by step instruction',
  'Problem with %',
  'My % has a problem',
  'When is a %',
  'What to do if a %',
  'Why does my %',
  'Why doesn’t my %',
  'What if a %',
  'alternatives %',
  'My % is',
  'When does %',
  'Is a %',
]

export const personInvolvedQualifiers = [
  'Why do	%',
  'Are	%',
  'How many	%',
  'How much do	%',
  'Tips for	%',
  'How much	%',
  'Best % for',
  'What to do if	%',
  'ideas %',
  'alternatives	%',
  'Why are	%',
  'How to make	%',
  '% vs',
  'Why can’t %',
  'Why don’t %',
  'Which	%',
  'Should	%',
  'What is the difference between	%',
  'What	%',
  'How do	%',
  'Aren’t	%',
  'What if	%',
]

export const actionPhraseQualiiers = [
  'How to %',
  'How do you %',
  'When to %',
  'Best way to %',
  'Should you %',
  'What if you %',
  'step by step instructions %',
]

export const continuousVerbQualifiers = [
  'What %',
  'Can %',
  'Will %',
  'Which %',
  'What is the difference between %',
  'How to make %',
  'Pros and cons of %',
  'Tips for %',
  'Why does %',
  'What to do if %',
  '% alternatives',
  'ideas %',
  'Will %',
  'Is %',
  'Isn’t %',
  'Why is %',
  'Why doesn’t %',
  'How much %',
  'Why can’t %',
  'How does %',
]