import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Card, Button } from "@tremor/react";
import LayoutMain from '@/components/Layouts/LayoutMain';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='w-full max-w-screen-sm mx-auto'>
          <Card>
            <h1 className='font-bold'>Hello</h1>
          </Card>
          <Button size="lg" onClick={() => console.log("clicked")}>
            Read more
          </Button>
        </div>
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page: any) {
  return (
    <LayoutMain>
      {page}
    </LayoutMain>
  )
}
